# Generated by Django 5.0.6 on 2024-07-05 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manajemen_buku', '0001_initial'),
        ('manajemen_pengguna', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_peminjaman', models.DateField(auto_now_add=True)),
                ('tanggal_pengembalian', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='dipinjam', max_length=50)),
                ('buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peminjaman', to='manajemen_buku.buku')),
                ('pengguna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peminjaman', to='manajemen_pengguna.pengguna')),
            ],
        ),
    ]
